### ISSUE TITLE
Memory Consumption Bug on Homepage

### ISSUE THREAD

**Issue by sethjones** [riftdweb/rift#49]
**What happened**:  Upon loading the rift.sh homepage (after redirect), the page continues to consume memory until Firefox prompts user to stop the page due to unresponsiveness.  

**What you expected to happen**:  Site completes loading and is available for usage.

**How to reproduce it (as minimally and precisely as possible)**: Load the homepage, while not signed into skynet. Let it sit for a few minutes <5m.

**Anything else we need to know?**:

**Environment**:
- User OS & Browser: Manjaro/W10/MacOs (11.6.1) x64: Firefox 95.0 x64
- Browser Extensions: Dark Reader, ublock origin, privacy badger
- Others: Do not track always enabled, Not signed into skynet

Tested and confirmed in private browser session without any extensions.

**Comment by alexfreska** [comment]
Oof, this was a bad bug - thank you so much for the clear bug report! 🥇 

The User Profile DAC dependencies was the culprit, the library has been disabled and the issue should be gone. Please let me know if you still see the behaviour!

**Comment by sethjones** [comment]
Quick test was unable to recreate it.
